FROM ubuntu:bionic

RUN apt-get update && \
    apt-get install -y unzip libncurses-dev dialog bc gcc-aarch64-linux-gnu libc6-dev-arm64-cross device-tree-compiler git ca-certificates build-essential wget fakeroot debhelper gawk kmod cpio bison flex python python-dev swig --no-install-recommends
